[env:esp32-s3-supermini]
platform = espressif32
board = esp32s3box
framework = arduino

board_build.mcu = esp32s3
board_build.f_cpu = 240000000L
board_build.arduino.memory_type = qio_opi

; Override board VID/PID at the board definition level to avoid
; redefinition conflicts with pins_arduino.h
board_build.extra_flags =
    -DARDUINO_USB_MODE=0
    -DARDUINO_USB_CDC_ON_BOOT=0

build_flags =
    -DBOARD_HAS_PSRAM
    -DCONFIG_ARDUINO_LOOP_STACK_SIZE=8192
    ; Corsair Commander Pro USB identity
    -DCORSAIR_USB_VID=0x1b1c
    -DCORSAIR_USB_PID=0x0c10

lib_deps =
    paulstoffregen/OneWire
    milesburton/DallasTemperature
    bblanchon/ArduinoJson

monitor_speed = 115200
#monitor_port = /dev/ttyACM0
#upload_port = /dev/ttyACM0
